version: '3.1'

volumes:
  app:

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
     - "8000:5000"
