version: '3.1'

volumes:
  app:
  db:

services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
     - "8000:5000"

  db:
    image: postgres

    env_file:
      - .env

    volumes:
      - db:/var/lib/postgresql

    ports:
      - "8432:5432"
