"""empty message

Revision ID: c4ecb27c9ce8
Revises: 
Create Date: 2017-10-24 13:37:01.205619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ecb27c9ce8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clantag', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_clantag'), 'clan', ['clantag'], unique=True)
    op.create_table('clanner_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clanner_user_email'), 'clanner_user', ['email'], unique=True)
    op.create_index(op.f('ix_clanner_user_username'), 'clanner_user', ['username'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usertag', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trophies', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_usertag'), 'player', ['usertag'], unique=True)
    op.create_table('clan_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('week_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donations', sa.Integer(), nullable=True),
    sa.Column('crowns', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('clan_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_player_id'], ['clan_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('week_data')
    op.drop_table('clan_player')
    op.drop_index(op.f('ix_player_usertag'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_clanner_user_username'), table_name='clanner_user')
    op.drop_index(op.f('ix_clanner_user_email'), table_name='clanner_user')
    op.drop_table('clanner_user')
    op.drop_index(op.f('ix_clan_clantag'), table_name='clan')
    op.drop_table('clan')
    # ### end Alembic commands ###
